FROM golang:1.21.1 as base

FROM base as built

WORKDIR /go/app/api
COPY . .

# Copy the config directory into the image
COPY config/ /go/app/api/config/

ENV CGO_ENABLED=0

RUN go mod download
RUN go mod verify
RUN go generate ./ent
RUN go build -o /tmp/main ./*.go

FROM busybox
COPY --from=built /tmp/main /usr/bin/main
COPY --from=built /go/app/api/config/ /usr/bin/config/

CMD ["./usr/bin/main"]